# Generated by Django 5.2.15 on 2026-10-06 10:31

from django.db import migrations, models


SECTION_COLUMNS = [
    "heading_color", "heading_size", "sub_heading_color", "sub_heading_size",
    "text_color", "text_size", "gold_line_color",
]


def add_missing_section_columns(apps, schema_editor):
    """يضيف أعمدة ألوان الأقسام فقط إذا مش موجودة (آمن على قاعدة السيرفر وعلى قاعدة جديدة)"""
    model = apps.get_model("award", "SectionBackground")
    table = model._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing = {c.name for c in schema_editor.connection.introspection.get_table_description(cursor, table)}
    for name in SECTION_COLUMNS:
        if name not in existing:
            schema_editor.add_field(model, model._meta.get_field(name))


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0025_herocard"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="المسار"
                    ),
                ),
                ("content", models.BinaryField(verbose_name="المحتوى")),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="الحجم (بايت)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ملف مخزّن",
                "verbose_name_plural": "الصور المخزّنة في قاعدة البيانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="footercontent",
            options={
                "verbose_name": "تحرير محتوى الفوتر (أسفل الصفحة)",
                "verbose_name_plural": "تحرير محتوى الفوتر (أسفل الصفحة)",
            },
        ),
        migrations.AlterModelOptions(
            name="homecontent",
            options={
                "verbose_name": "تحرير محتوى الصفحة الرئيسية (A to Z)",
                "verbose_name_plural": "تحرير محتوى الصفحة الرئيسية (A to Z)",
            },
        ),
        migrations.AlterModelOptions(
            name="slideshowcard",
            options={
                "ordering": ["order"],
                "verbose_name": "بطاقة عرض شفافة",
                "verbose_name_plural": "بطاقات العرض الشفافة (Slideshow)",
            },
        ),
        migrations.AlterModelOptions(
            name="successpagecontent",
            options={
                "verbose_name": "تحرير صفحة النجاح (بعد التسجيل)",
                "verbose_name_plural": "تحرير صفحة النجاح (بعد التسجيل)",
            },
        ),
        # العمود image_url يبقى بقاعدة البيانات (nullable) — نشيله من الـ state فقط بدون فقدان بيانات
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="slideshowcard", name="image_url"),
            ],
            database_operations=[],
        ),
        # أعمدة الألوان أُضيفت سابقاً بـ RunSQL في 0023 (موجودة على السيرفر)
        # هنا نسجّلها بالـ state ونضيفها للقاعدة فقط إذا كانت ناقصة
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="sectionbackground",
                    name="gold_line_color",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=7,
                        verbose_name="لون الخط الذهبي تحت العنوان",
                    ),
                ),
                migrations.AddField(
                    model_name="sectionbackground",
                    name="heading_color",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=7,
                        verbose_name="لون العنوان الرئيسي (h2)",
                    ),
                ),
                migrations.AddField(
                    model_name="sectionbackground",
                    name="heading_size",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=6,
                        verbose_name="حجم العنوان الرئيسي (مثال: 2.2rem)",
                    ),
                ),
                migrations.AddField(
                    model_name="sectionbackground",
                    name="sub_heading_color",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=7,
                        verbose_name="لون العناوين الفرعية (h3, h4, h5)",
                    ),
                ),
                migrations.AddField(
                    model_name="sectionbackground",
                    name="sub_heading_size",
                    field=models.CharField(
                        blank=True,
                        default="",
                        max_length=6,
                        verbose_name="حجم العناوين الفرعية",
                    ),
                ),
                migrations.AddField(
                    model_name="sectionbackground",
                    name="text_color",
                    field=models.CharField(
                        blank=True, default="", max_length=7, verbose_name="لون النصوص (p, li)"
                    ),
                ),
                migrations.AddField(
                    model_name="sectionbackground",
                    name="text_size",
                    field=models.CharField(
                        blank=True, default="", max_length=6, verbose_name="حجم النصوص"
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(add_missing_section_columns, migrations.RunPython.noop),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_side_image",
            field=models.ImageField(
                blank=True,
                help_text="تظهر بجانب صورة الخلفية الرئيسية (يسار على الكمبيوتر، وتحتها على الموبايل). اتركها فارغة لعرض الصورة الرئيسية بعرض كامل.",
                null=True,
                upload_to="site_media/",
                verbose_name="صورة جانبية بجانب الصورة الرئيسية (الهيرو)",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="البريد"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="تمت القراءة؟"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(verbose_name="الرسالة"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=200, verbose_name="الاسم"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=300, verbose_name="الموضوع"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="الإجابة"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=500, verbose_name="السؤال"),
        ),
        migrations.AlterField(
            model_name="footercontent",
            name="about_text",
            field=models.TextField(
                default="مبادرة تهدف لتكريم العطاء التطوعي للشباب اليافع في الأردن، تخليداً لمسيرة السيدة انتصار عباس جردانة.",
                verbose_name="نص عن الجائزة في الفوتر",
            ),
        ),
        migrations.AlterField(
            model_name="footercontent",
            name="copyright_text",
            field=models.CharField(
                default="جميع الحقوق محفوظة 2025 جائزة انتصار عباس جردانة للثقافة والتعليم",
                max_length=200,
                verbose_name="نص حقوق النشر",
            ),
        ),
        migrations.AlterField(
            model_name="herocard",
            name="body_text",
            field=models.TextField(blank=True, default="", verbose_name="النص الداخلي"),
        ),
        migrations.AlterField(
            model_name="herocard",
            name="card_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.55,
                max_digits=3,
                verbose_name="شفافية البطاقة (0=شفافة، 1=معتمة)",
            ),
        ),
        migrations.AlterField(
            model_name="herocard",
            name="font_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="لون الخط"
            ),
        ),
        migrations.AlterField(
            model_name="herocard",
            name="font_weight",
            field=models.CharField(
                default="600", max_length=3, verbose_name="وزن الخط"
            ),
        ),
        migrations.AlterField(
            model_name="herocard",
            name="heading",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="العنوان"
            ),
        ),
        migrations.AlterField(
            model_name="herocard",
            name="is_enabled",
            field=models.BooleanField(default=False, verbose_name="تفعيل البطاقة؟"),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="about_text",
            field=models.TextField(
                default="تخليداً لذكرى السيدة انتصار عباس جردانة، أُطلقت هذه الجائزة لتكريم المبادرات التطوعية...",
                verbose_name="نص عن الجائزة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="btn_navbar",
            field=models.CharField(
                default="سجل الآن", max_length=100, verbose_name="زر النافبار العلوي"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="hero_title",
            field=models.CharField(
                default="جائزة انتصار عباس جردانة",
                max_length=200,
                verbose_name="العنوان الرئيسي الكبير",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="mission_text",
            field=models.TextField(
                default="تكريم القدرات التطوعية ودعم المبادرات كفعل نهضوي.",
                verbose_name="نص الرسالة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="vision_text",
            field=models.TextField(
                default="مجتمع نابض بالشغف والعطاء، يحتضن المبادرات.",
                verbose_name="نص الرؤية",
            ),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="التصنيف"
            ),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="gallery/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="media_type",
            field=models.CharField(
                choices=[("image", "صورة"), ("video", "فيديو")],
                default="image",
                max_length=10,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="title",
            field=models.CharField(max_length=200, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="رابط يوتيوب"),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(verbose_name="المحتوى"),
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateField(verbose_name="التاريخ"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="news/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="منشور؟"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=300, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="bg_color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                verbose_name="لون خلفية بديل (بدون صورة)",
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="bg_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="backgrounds/",
                verbose_name="صورة الخلفية",
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="enable_overlay",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل الطبقة الشفافة؟"
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="is_parallax",
            field=models.BooleanField(
                default=True, verbose_name="تفعيل الحركة (Parallax)؟"
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="overlay_color",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="لون الطبقة"
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="overlay_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.7,
                max_digits=3,
                verbose_name="نسبة الشفافية",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="موعد إغلاق التسجيل (للعداد التنازلي)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_media/",
                verbose_name="شعار الموقع (Logo) - يظهر في الهيدر والفوتر",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="border_radius",
            field=models.CharField(
                default="16px",
                max_length=6,
                verbose_name="استدارة الزوايا (مثال: 16px أو 0 أو 50%)",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="card_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.45,
                max_digits=3,
                verbose_name="شفافية البطاقة (0.0 = شفافة تماماً، 1.0 = معتمة)",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="font_size",
            field=models.CharField(
                default="1rem",
                max_length=6,
                verbose_name="حجم الخط (مثال: 1rem أو 18px أو 1.2em)",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="font_weight",
            field=models.CharField(
                choices=[
                    ("300", "خفيف (300)"),
                    ("400", "عادي (400)"),
                    ("600", "شبه سميك (600)"),
                    ("700", "سميك (Bold)"),
                    ("900", "أسود سميك (900)"),
                ],
                default="400",
                max_length=3,
                verbose_name="وزن الخط",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="مطلوبة لنوع (صورة) و(صورة+نص)",
                null=True,
                upload_to="slideshow/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="بديل عن رابط يوتيوب — mp4/webm",
                null=True,
                upload_to="slideshow/videos/",
                verbose_name="ملف فيديو (رفع مباشر)",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="مثال: https://www.youtube.com/embed/VIDEO_ID",
                null=True,
                verbose_name="رابط فيديو (يوتيوب أو Vimeo)",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(upload_to="sponsors/", verbose_name="شعار الجهة"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="tier",
            field=models.CharField(
                choices=[
                    ("platinum", "بلاتيني"),
                    ("gold", "ذهبي"),
                    ("silver", "فضي"),
                    ("bronze", "برونزي"),
                ],
                default="gold",
                max_length=20,
                verbose_name="مستوى الرعاية",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="رابط الموقع"),
        ),
        migrations.AlterField(
            model_name="successpagecontent",
            name="sub_text",
            field=models.TextField(
                default="شكراً لمشاركتكم في جائزة انتصار عباس جردانة. سيتم مراجعة الطلب.",
                verbose_name="النص الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="themesetting",
            name="custom_css",
            field=models.TextField(
                blank=True,
                help_text="اكتب أو الصق أكواد CSS هنا لتغيير تصميم الموقع بدون لمس الكود الأساسي",
                null=True,
                verbose_name="CSS مخصص (لتغيير ألوان صفحات أو أحجام خطوط معينة)",
            ),
        ),
        migrations.AlterField(
            model_name="themesetting",
            name="font_size",
            field=models.CharField(
                default="16px",
                max_length=4,
                verbose_name="حجم الخط الأساسي (مثال: 16px أو 18px)",
            ),
        ),
        migrations.AlterField(
            model_name="themesetting",
            name="primary_color",
            field=models.CharField(
                default="#0a1632",
                max_length=7,
                verbose_name="اللون الأساسي (الأزرق الداكن)",
            ),
        ),
        migrations.AlterField(
            model_name="tickeritem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="مفعّل؟"),
        ),
        migrations.AlterField(
            model_name="tickeritem",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="ticker/",
                verbose_name="لوغو (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="tickeritem",
            name="message_html",
            field=models.TextField(verbose_name="النص (يدعم HTML)"),
        ),
        migrations.AlterField(
            model_name="tickeritem",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="tickersetting",
            name="bg_color",
            field=models.CharField(
                default="#0a1632", max_length=7, verbose_name="لون الخلفية"
            ),
        ),
        migrations.AlterField(
            model_name="tickersetting",
            name="bg_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.95,
                max_digits=3,
                verbose_name="شفافية الخلفية",
            ),
        ),
        migrations.AlterField(
            model_name="tickersetting",
            name="fade_width",
            field=models.CharField(
                default="150px", max_length=5, verbose_name="مسافة التلاشي"
            ),
        ),
        migrations.AlterField(
            model_name="tickersetting",
            name="font_color",
            field=models.CharField(
                default="#c5a059", max_length=7, verbose_name="لون الخط"
            ),
        ),
        migrations.AlterField(
            model_name="tickersetting",
            name="scroll_speed",
            field=models.IntegerField(
                default=60,
                help_text="رقم أكبر = أسرع. المقترح: 40 بطيء، 60 متوسط، 100 سريع (من 10 إلى 300).",
                verbose_name="السرعة (بكسل/ثانية)",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="date_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="التاريخ (مثال: 17 سبتمبر 2025) - اتركه فارغاً لو مش تاريخ",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fa-check-circle",
                max_length=50,
                verbose_name="أيقونة FontAwesome (مثال: fa-bullhorn)",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="is_highlighted",
            field=models.BooleanField(
                default=False, verbose_name="مميز؟ (مثل حفل الختام)"
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="النبذة"),
        ),
        migrations.AlterField(
            model_name="winner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="winners/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="winner",
            name="rank",
            field=models.IntegerField(verbose_name="المركز"),
        ),
        migrations.AlterField(
            model_name="winner",
            name="year",
            field=models.IntegerField(verbose_name="سنة الفوز"),
        ),
    ]
