# Generated by Django 5.2.15 on 2026-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0026_hero_side_image_storedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="hero_side_video",
            field=models.FileField(
                blank=True,
                help_text="بديل عن الصورة الجانبية — يعمل تلقائياً بدون صوت وبشكل متكرر. له الأولوية على الصورة.",
                null=True,
                upload_to="site_media/videos/",
                verbose_name="فيديو جانبي (رفع ملف mp4)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_side_video_url",
            field=models.URLField(
                blank=True,
                help_text="مثال: https://www.youtube.com/watch?v=XXXX — يُستخدم إذا لم يُرفع ملف فيديو.",
                null=True,
                verbose_name="أو رابط فيديو يوتيوب للجانب",
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="section_id",
            field=models.CharField(
                choices=[
                    ("home", "أعلى الصفحة الرئيسية (الصورة الكبيرة)"),
                    ("stats", "الإحصائيات"),
                    ("about", "عن الجائزة"),
                    ("fields", "مجالات العمل التطوعي"),
                    ("timeline", "الجدول الزمني"),
                    ("apply", "طلب التقديم"),
                    ("prizes", "الجوائز"),
                    ("judges", "لجنة التحكيم"),
                    ("footer", "الفوتر"),
                ],
                max_length=20,
                unique=True,
                verbose_name="اختر القسم",
            ),
        ),
    ]
