# Generated by Django 5.2.15 on 2026-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0027_hero_side_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="media_file",
            field=models.FileField(
                max_length=500,
                upload_to="hero_slideshow/",
                verbose_name="الملف (صورة أو فيديو)",
            ),
        ),
        migrations.AlterField(
            model_name="judge",
            name="image",
            field=models.ImageField(
                max_length=500, upload_to="judges/", verbose_name="الصورة الشخصية"
            ),
        ),
        migrations.AlterField(
            model_name="mediagallery",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="gallery/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="news/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.FileField(
                max_length=500, upload_to="photos/", verbose_name="الصورة"
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="bg_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="backgrounds/",
                verbose_name="صورة الخلفية",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_background",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="site_media/",
                verbose_name="خلفية الصفحة الرئيسية (صورة)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_side_image",
            field=models.ImageField(
                blank=True,
                help_text="تظهر بجانب صورة الخلفية الرئيسية (يسار على الكمبيوتر، وتحتها على الموبايل). اتركها فارغة لعرض الصورة الرئيسية بعرض كامل.",
                max_length=500,
                null=True,
                upload_to="site_media/",
                verbose_name="صورة جانبية بجانب الصورة الرئيسية (الهيرو)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_side_video",
            field=models.FileField(
                blank=True,
                help_text="بديل عن الصورة الجانبية — يعمل تلقائياً بدون صوت وبشكل متكرر. له الأولوية على الصورة.",
                max_length=500,
                null=True,
                upload_to="site_media/videos/",
                verbose_name="فيديو جانبي (رفع ملف mp4)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_video",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="site_media/",
                verbose_name="خلفية الصفحة الرئيسية (فيديو)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="site_media/",
                verbose_name="شعار الموقع (Logo) - يظهر في الهيدر والفوتر",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="مطلوبة لنوع (صورة) و(صورة+نص)",
                max_length=500,
                null=True,
                upload_to="slideshow/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="slideshowcard",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="بديل عن رابط يوتيوب — mp4/webm",
                max_length=500,
                null=True,
                upload_to="slideshow/videos/",
                verbose_name="ملف فيديو (رفع مباشر)",
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="logo",
            field=models.ImageField(
                max_length=500, upload_to="sponsors/", verbose_name="شعار الجهة"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="document",
            field=models.FileField(
                max_length=500, upload_to="submissions/", verbose_name="ملف البحث (PDF)"
            ),
        ),
        migrations.AlterField(
            model_name="successstory",
            name="image",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to="success_stories/",
                verbose_name="الصورة",
            ),
        ),
        migrations.AlterField(
            model_name="tickeritem",
            name="logo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="ticker/",
                verbose_name="لوغو (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="modal_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="timeline/",
                verbose_name="صورة البطاقة المنبثقة",
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="winners/",
                verbose_name="الصورة",
            ),
        ),
    ]
