# Generated by Django 5.2.15 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0028_longer_file_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_side_video",
            field=models.FileField(
                blank=True,
                help_text="بديل عن الصورة الجانبية — يعمل تلقائياً بدون صوت مرة واحدة. له الأولوية على الصورة.",
                max_length=500,
                null=True,
                upload_to="site_media/videos/",
                verbose_name="فيديو جانبي (رفع ملف mp4)",
            ),
        ),
    ]
