# Generated by Django 5.2.15 on 2026-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0029_side_video_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="Principle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="اسم المبدأ")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="شرح مختصر (اختياري)"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-star",
                        help_text="مثال: fa-hand-holding-heart أو fa-lightbulb — القائمة: fontawesome.com/icons",
                        max_length=60,
                        verbose_name="أيقونة FontAwesome",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر؟")),
            ],
            options={
                "verbose_name": "مبدأ",
                "verbose_name_plural": "مبادئ الجائزة (بطاقات عن الجائزة)",
                "ordering": ["order", "pk"],
            },
        ),
    ]
