# Generated by Django 5.2.15 on 2026-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0031_copy_principles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heroslide",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "شريحة (صورة / فيديو)",
                "verbose_name_plural": "بطاقة الفيديو والصور — الشرائح",
            },
        ),
        migrations.AddField(
            model_name="heroslide",
            name="poster",
            field=models.ImageField(
                blank=True,
                help_text="تظهر قبل الضغط على تشغيل. بدونها يظهر أول مشهد من الفيديو.",
                max_length=500,
                null=True,
                upload_to="hero_slideshow/",
                verbose_name="صورة غلاف للفيديو (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="عنوان صغير على الشريحة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="مثال: https://www.youtube.com/watch?v=XXXX",
                verbose_name="رابط يوتيوب",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="slide_seconds",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="في بطاقة الشرائح. الفيديو لا يتبدّل أثناء تشغيله.",
                verbose_name="مدة عرض كل صورة (ثوانٍ)",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="ظاهرة؟"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="media_file",
            field=models.FileField(
                blank=True,
                help_text="للصورة أو الفيديو. اتركه فارغاً إذا كان النوع «فيديو يوتيوب».",
                max_length=500,
                upload_to="hero_slideshow/",
                verbose_name="الملف (صورة أو فيديو mp4)",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "صورة"),
                    ("video", "فيديو (ملف)"),
                    ("youtube", "فيديو يوتيوب"),
                ],
                default="image",
                max_length=10,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="hero_side_video",
            field=models.FileField(
                blank=True,
                help_text="يُستخدم فقط إذا لم تُضف شرائح. يعمل عند الضغط عليه.",
                max_length=500,
                null=True,
                upload_to="site_media/videos/",
                verbose_name="فيديو جانبي (رفع ملف mp4)",
            ),
        ),
    ]
