# Generated by Django 5.2.15 on 2026-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0032_hero_slides"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="click_action",
            field=models.CharField(
                choices=[
                    ("zoom", "تكبير الصورة بملء الشاشة"),
                    ("link", "فتح رابط"),
                    ("none", "لا شيء"),
                ],
                default="zoom",
                help_text="للصور فقط. الفيديو يعمل دائماً عند الضغط عليه.",
                max_length=10,
                verbose_name="عند الضغط على الصورة",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="link_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مثال: /submit/  أو  /news/  أو رابط كامل https://...",
                max_length=500,
                verbose_name="الرابط (إذا اخترت «فتح رابط»)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="slide_show_timer",
            field=models.BooleanField(
                default=True,
                help_text="خط رفيع يمتلئ حتى تتبدّل الشريحة التالية.",
                verbose_name="إظهار شريط الوقت أعلى بطاقة الشرائح",
            ),
        ),
    ]
