# Generated by Django 5.2.15 on 2026-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0033_slide_click_timer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footercontent",
            name="address",
            field=models.CharField(
                default="المملكة الأردنية الهاشمية",
                max_length=1000,
                verbose_name="العنوان",
            ),
        ),
        migrations.AlterField(
            model_name="footercontent",
            name="copyright_text",
            field=models.CharField(
                default="جميع الحقوق محفوظة 2025 جائزة انتصار عباس جردانة للثقافة والتعليم",
                max_length=1000,
                verbose_name="نص حقوق النشر",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="btn_hero",
            field=models.CharField(
                default="تقدم لمشروعك الآن",
                max_length=1000,
                verbose_name="زر الصفحة الرئيسية",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="btn_navbar",
            field=models.CharField(
                default="سجل الآن", max_length=1000, verbose_name="زر النافبار العلوي"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="condition_1",
            field=models.CharField(
                default="نطاق العمل داخل المملكة الأردنية الهاشمية.",
                max_length=1000,
                verbose_name="الشرط الأول",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="condition_2",
            field=models.CharField(
                default="مراعاة المبادئ العامة ومجالات الجائزة.",
                max_length=1000,
                verbose_name="الشرط الثاني",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="condition_3",
            field=models.CharField(
                default="الالتزام بالميثاق الأخلاقي للعمل التطوعي.",
                max_length=1000,
                verbose_name="الشرط الثالث",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="condition_4",
            field=models.CharField(
                default="الفئة المستهدفة: طلبة التاسع - الثاني عشر.",
                max_length=1000,
                verbose_name="الشرط الرابع",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="condition_5",
            field=models.CharField(
                default="تقديم البحث بصيغة PDF (15-20 صفحة).",
                max_length=1000,
                verbose_name="الشرط الخامس",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="hero_subtitle",
            field=models.TextField(
                default="للثقافة والتعليم", verbose_name="العنوان الفرعي (النص المتحرك)"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="hero_title",
            field=models.CharField(
                default="جائزة انتصار عباس جردانة",
                max_length=1000,
                verbose_name="العنوان الرئيسي الكبير",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="principle_1",
            field=models.CharField(
                default="العطاء", max_length=1000, verbose_name="المبدأ الأول"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="principle_2",
            field=models.CharField(
                default="الريادة والابتكار",
                max_length=1000,
                verbose_name="المبدأ الثاني",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="principle_3",
            field=models.CharField(
                default="الاستدامة", max_length=1000, verbose_name="المبدأ الثالث"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="principle_4",
            field=models.CharField(
                default="الأثر والتأثر", max_length=1000, verbose_name="المبدأ الرابع"
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="prize_1_desc",
            field=models.CharField(
                default="1500 دينار + درع العمل التطوعي المتميز",
                max_length=1000,
                verbose_name="وصف الجائزة الأولى",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="prize_2_desc",
            field=models.CharField(
                default="1000 دينار + درع الاستدامة والتأثير",
                max_length=1000,
                verbose_name="وصف الجائزة الثانية",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="prize_3_desc",
            field=models.CharField(
                default="500 دينار + درع أفضل فكرة ريادية",
                max_length=1000,
                verbose_name="وصف الجائزة الثالثة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="step_1",
            field=models.CharField(
                default="الاطلاع على دليل الجائزة ومعايير التحكيم.",
                max_length=1000,
                verbose_name="الخطوة الأولى",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="step_2",
            field=models.CharField(
                default="حضور اللقاء التعريفي بالمدرسة.",
                max_length=1000,
                verbose_name="الخطوة الثانية",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="step_3",
            field=models.CharField(
                default="تعبئة طلب الترشح الإلكتروني.",
                max_length=1000,
                verbose_name="الخطوة الثالثة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="step_4",
            field=models.CharField(
                default="تقديم البحث والصور والفيديوهات.",
                max_length=1000,
                verbose_name="الخطوة الرابعة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="step_5",
            field=models.CharField(
                default="تحديد ضابط ارتباط للمتابعة والتحكيم.",
                max_length=1000,
                verbose_name="الخطوة الخامسة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title_about",
            field=models.CharField(
                default="عن الجائزة",
                max_length=1000,
                verbose_name="عنوان قسم عن الجائزة",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title_apply",
            field=models.CharField(
                default="طلب التقديم للجائزة",
                max_length=1000,
                verbose_name="عنوان قسم التقديم",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title_fields",
            field=models.CharField(
                default="مجالات العمل التطوعي",
                max_length=1000,
                verbose_name="عنوان قسم المجالات",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title_judges",
            field=models.CharField(
                default="لجنة التحكيم",
                max_length=1000,
                verbose_name="عنوان قسم لجنة التحكيم",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title_prizes",
            field=models.CharField(
                default="قيمة الجوائز",
                max_length=1000,
                verbose_name="عنوان قسم الجوائز",
            ),
        ),
        migrations.AlterField(
            model_name="homecontent",
            name="title_timeline",
            field=models.CharField(
                default="الإطار الزمني لمراحل الجائزة",
                max_length=1000,
                verbose_name="عنوان قسم الجدول الزمني",
            ),
        ),
    ]
