# Generated by Django 5.2.15 on 2026-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0034_longer_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionbackground",
            name="bg_color_2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مع «لون خلفية بديل» يصبح القسم تدرّجاً بين اللونين. بدونه يُصنع تدرّج تلقائي من اللون الأول.",
                max_length=7,
                verbose_name="لون التدرّج الثاني (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="sectionbackground",
            name="overlay_color_2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                verbose_name="لون الطبقة الثاني (تدرّج، اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="flip_style",
            field=models.CharField(
                choices=[("navy", "كحلي مع ذهبي"), ("gold", "معكوس: ذهبي مع كحلي")],
                default="navy",
                max_length=10,
                verbose_name="ألوان البطاقات القلابة (المجالات)",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="site_style",
            field=models.CharField(
                choices=[
                    ("glass", "كحلي وذهبي — تدرّج لوني وزجاجي في كل الموقع"),
                    ("classic", "الكلاسيكي — أقسام بيضاء ورمادية"),
                ],
                default="glass",
                help_text="يمكنك الرجوع للنمط الكلاسيكي في أي وقت.",
                max_length=10,
                verbose_name="نمط الموقع",
            ),
        ),
    ]
