# Generated by Django 5.2.15 on 2026-10-07 15:03

from django.db import migrations, models


def to_classic(apps, schema_editor):
    # التدرّج والزجاج في قسم المجالات فقط — باقي الموقع كما كان
    apps.get_model('award', 'ThemeSetting').objects.update(site_style='classic')


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0035_gradients_glass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionbackground",
            name="bg_color_2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مع «لون خلفية بديل» يصبح القسم تدرّجاً بين اللونين. (قسم المجالات متدرّج تلقائياً)",
                max_length=7,
                verbose_name="لون التدرّج الثاني (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="themesetting",
            name="site_style",
            field=models.CharField(
                choices=[
                    ("classic", "الكلاسيكي — أقسام بيضاء ورمادية"),
                    ("glass", "تدرّج لوني وزجاجي في كل الموقع"),
                ],
                default="classic",
                help_text="يمكنك الرجوع للنمط الكلاسيكي في أي وقت.",
                max_length=10,
                verbose_name="نمط الموقع",
            ),
        ),
        migrations.RunPython(to_classic, migrations.RunPython.noop),
    ]
