# Generated by Django 5.2.15 on 2026-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0036_classic_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="تظهر على الوجه الأمامي للبطاقة القلابة مع طبقة داكنة ليبقى العنوان واضحاً.",
                max_length=500,
                null=True,
                upload_to="fields/",
                verbose_name="صورة خلفية غلاف البطاقة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="cover_overlay",
            field=models.DecimalField(
                decimal_places=2,
                default=0.55,
                max_digits=3,
                verbose_name="تعتيم صورة الغلاف (0 = بدون، 1 = معتم)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="cd_show_days",
            field=models.BooleanField(
                default=True, verbose_name="العداد: إظهار الأيام"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="cd_show_hours",
            field=models.BooleanField(
                default=True, verbose_name="العداد: إظهار الساعات"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="cd_show_minutes",
            field=models.BooleanField(
                default=True, verbose_name="العداد: إظهار الدقائق"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="cd_show_seconds",
            field=models.BooleanField(
                default=True, verbose_name="العداد: إظهار الثواني"
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="bar_height",
            field=models.PositiveSmallIntegerField(
                default=38,
                help_text="المقترح بين 32 و 60",
                verbose_name="ارتفاع الشريط (بكسل)",
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="effects_on_logos",
            field=models.BooleanField(
                default=False,
                verbose_name="تطبيق النبض والتلاشي على صور الأخبار أيضاً؟",
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="font_size",
            field=models.CharField(
                default="0.95rem",
                help_text="مثال: 0.95rem (عادي) — 1.1rem (أكبر) — 16px",
                max_length=8,
                verbose_name="حجم الخط",
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="logo_size",
            field=models.PositiveSmallIntegerField(
                default=24, verbose_name="حجم الصور في الشريط (بكسل)"
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="sep_fade",
            field=models.BooleanField(
                default=False, verbose_name="تلاشي الصورة الفاصلة (يظهر ويختفي)؟"
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="sep_fade_seconds",
            field=models.DecimalField(
                decimal_places=1,
                default=2.4,
                help_text="رقم أصغر = أسرع",
                max_digits=3,
                verbose_name="سرعة التلاشي (ثوانٍ)",
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="sep_pulse",
            field=models.BooleanField(default=True, verbose_name="نبض الصورة الفاصلة؟"),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="sep_pulse_seconds",
            field=models.DecimalField(
                decimal_places=1,
                default=1.6,
                help_text="رقم أصغر = أسرع",
                max_digits=3,
                verbose_name="سرعة النبض (ثوانٍ)",
            ),
        ),
        migrations.AddField(
            model_name="tickersetting",
            name="separator_image",
            field=models.ImageField(
                blank=True,
                help_text="تظهر في الوسط بين كل خبرين بدل النجمة الصغيرة.",
                max_length=500,
                null=True,
                upload_to="ticker/",
                verbose_name="صورة فاصلة بين الأخبار (اختياري)",
            ),
        ),
    ]
