# Generated by Django 5.2.15 on 2026-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0037_ticker_countdown_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroTextSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="العنوان"
                    ),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, default="", verbose_name="النص"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر؟")),
            ],
            options={
                "verbose_name": "نص متبدّل",
                "verbose_name_plural": "النصوص المتبدّلة تحت الفيديو",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="herocard",
            name="min_seconds",
            field=models.PositiveSmallIntegerField(
                default=4, verbose_name="أقل مدة لكل نص (ثوانٍ)"
            ),
        ),
        migrations.AddField(
            model_name="herocard",
            name="reading_speed",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="مدة كل نص تُحسب من طوله: رقم أصغر = وقت أطول للقراءة. المقترح 12–18.",
                verbose_name="سرعة القراءة (حرف في الثانية)",
            ),
        ),
        migrations.AddField(
            model_name="herocard",
            name="show_arrows",
            field=models.BooleanField(default=True, verbose_name="إظهار سهمي التنقل"),
        ),
        migrations.AddField(
            model_name="herocard",
            name="text_effect",
            field=models.CharField(
                choices=[
                    ("fade", "تلاشي ناعم"),
                    ("slide", "انزلاق جانبي"),
                    ("up", "صعود من الأسفل"),
                    ("zoom", "تكبير"),
                    ("blur", "ضبابية ثم وضوح"),
                    ("flip", "قلب"),
                ],
                default="fade",
                max_length=10,
                verbose_name="حركة الانتقال بين النصوص",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo_size",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="المقترح بين 40 و 80",
                verbose_name="حجم الشعار على الكمبيوتر (بكسل)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo_size_mobile",
            field=models.PositiveSmallIntegerField(
                default=38, verbose_name="حجم الشعار على الموبايل (بكسل)"
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo_size_scrolled",
            field=models.PositiveSmallIntegerField(
                default=44, verbose_name="حجم الشعار بعد النزول في الصفحة (بكسل)"
            ),
        ),
    ]
