# Generated by Django 5.2.15 on 2026-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0038_logo_text_slides"),
    ]

    operations = [
        migrations.AddField(
            model_name="homecontent",
            name="title_sponsors",
            field=models.CharField(
                default="رعاة وشركاء النجاح",
                max_length=1000,
                verbose_name="عنوان قسم الرعاة والشركاء",
            ),
        ),
        migrations.AlterField(
            model_name="sectionbackground",
            name="section_id",
            field=models.CharField(
                choices=[
                    ("home", "أعلى الصفحة الرئيسية (الصورة الكبيرة)"),
                    ("stats", "الإحصائيات"),
                    ("about", "عن الجائزة"),
                    ("fields", "مجالات العمل التطوعي"),
                    ("timeline", "الجدول الزمني"),
                    ("apply", "طلب التقديم"),
                    ("prizes", "الجوائز"),
                    ("judges", "لجنة التحكيم"),
                    ("sponsors", "رعاة وشركاء النجاح"),
                    ("footer", "الفوتر"),
                ],
                max_length=20,
                unique=True,
                verbose_name="اختر القسم",
            ),
        ),
    ]
