# Generated by Django 5.2.15 on 2026-10-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0039_sponsors_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={
                "ordering": ["field", "order", "id"],
                "verbose_name": "مسار",
                "verbose_name_plural": "المسارات",
            },
        ),
        migrations.AddField(
            model_name="track",
            name="details_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="شرح مطوّل بعناوين وقوائم وصور — يظهر في صفحة المسار بعد جدول التفاصيل.",
                verbose_name="شرح تفصيلي (نص منسّق)",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="order",
            field=models.IntegerField(default=0, verbose_name="الترتيب"),
        ),
        migrations.AlterField(
            model_name="track",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="فقرة قصيرة تظهر أعلى الشرح وفي نتائج البحث.",
                null=True,
                verbose_name="نبذة قصيرة عن المسار (عربي)",
            ),
        ),
        migrations.CreateModel(
            name="TrackDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="البند")),
                (
                    "content",
                    models.TextField(
                        help_text="كل سطر جديد يظهر كنقطة منفصلة.",
                        verbose_name="التفاصيل",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: fa-users — fa-lightbulb — fa-list-check — fa-scale-balanced",
                        max_length=60,
                        verbose_name="أيقونة (اختياري)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="award.track",
                        verbose_name="المسار",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند تفاصيل",
                "verbose_name_plural": "جدول تفاصيل المسار",
                "ordering": ["order", "id"],
            },
        ),
    ]
