# Generated by Django 5.2.15 on 2026-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0040_track_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="المسار المعطّل يختفي من البطاقات والبحث ونموذج التسجيل.",
                verbose_name="مفعّل؟",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="notice_enabled",
            field=models.BooleanField(
                default=False, verbose_name="إظهار شريط الملاحظة؟"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="notice_speed",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="رقم أكبر = أسرع. المقترح 40–70.",
                verbose_name="سرعة الشريط (بكسل/ثانية)",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="notice_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="شريط متحرك أعلى شرح المسار — لإشعار فوري، مثل: «تم تمديد التقديم لهذا المسار حتى 30 نوفمبر».",
                max_length=500,
                verbose_name="نص شريط الملاحظة",
            ),
        ),
    ]
