# Generated by Django 5.2.15 on 2026-10-08 13:52

import award.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0041_track_active_notice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=500, verbose_name="إلى")),
                ("subject", models.CharField(max_length=255, verbose_name="الموضوع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "أُرسل"),
                            ("saved", "محفوظ (البريد غير مضبوط)"),
                            ("failed", "فشل"),
                        ],
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, default="", verbose_name="الخطأ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
            ],
            options={
                "verbose_name": "رسالة بريد",
                "verbose_name_plural": "سجل رسائل البريد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "طلب ترشح",
                "verbose_name_plural": "طلبات الترشح",
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="abstract",
            field=models.TextField(
                blank=True,
                default="",
                help_text="فقرة تشرح فكرة المشروع وأهدافه ونتائجه.",
                verbose_name="ملخص المشروع",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="صور، عرض تقديمي، ملف مضغوط…",
                max_length=500,
                upload_to=award.models.submission_upload,
                verbose_name="مرفق إضافي (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="internal_note",
            field=models.TextField(
                blank=True, default="", verbose_name="ملاحظات داخلية (للإدارة فقط)"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حساب المدرسة",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ref",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="رقم الطلب",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="revision_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخر موعد للتعديل"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="school_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="مثلاً: المطلوب تعديله. تُرسل مع إشعار تغيير الحالة.",
                verbose_name="ملاحظة للمدرسة (تظهر لها)",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الإرسال"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="supervisor",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="المعلم المشرف"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="team_members",
            field=models.TextField(
                blank=True,
                default="",
                help_text="كل اسم في سطر.",
                verbose_name="أسماء الطلبة المشاركين",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="document",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=award.models.submission_upload,
                verbose_name="ملف البحث (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="رقم الهاتف"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُرسل — بانتظار التدقيق"),
                    ("screening", "قيد التدقيق"),
                    ("revision", "مطلوب تعديل"),
                    ("judging", "قيد التحكيم"),
                    ("accepted", "مقبول"),
                    ("rejected", "غير مقبول"),
                    ("winner", "فائز"),
                    ("withdrawn", "مسحوب"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإسناد"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="ملاحظات المحكّم العامة"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("strong", "أوصي بشدة"),
                            ("yes", "أوصي"),
                            ("maybe", "محايد"),
                            ("no", "لا أوصي"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="التوصية",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ إنهاء التقييم"
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المحكّم",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="award.submission",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "إسناد تحكيم",
                "verbose_name_plural": "إسناد الطلبات للمحكّمين",
                "ordering": ["-assigned_at"],
                "unique_together": {("submission", "judge")},
            },
        ),
        migrations.CreateModel(
            name="AwardCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: الدورة الأولى",
                        max_length=200,
                        verbose_name="اسم الدورة",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="السنة")),
                ("opens_at", models.DateTimeField(verbose_name="بداية التسجيل")),
                (
                    "closes_at",
                    models.DateTimeField(
                        help_text="بعدها لا تُقبل طلبات جديدة. العداد التنازلي في الموقع يستخدم هذا الموعد.",
                        verbose_name="نهاية التسجيل",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="دورة واحدة فقط تكون حالية — اختيارها يلغي غيرها.",
                        verbose_name="الدورة الحالية؟",
                    ),
                ),
                (
                    "max_per_school",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = بلا حد.",
                        verbose_name="أقصى عدد طلبات للمدرسة",
                    ),
                ),
                (
                    "revision_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="عند طلب تعديل من المدرسة يُحدَّد آخر موعد تلقائياً.",
                        verbose_name="مهلة التعديل (أيام)",
                    ),
                ),
                (
                    "judges_per_submission",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="يُستخدم عند «توزيع تلقائي على المحكّمين».",
                        verbose_name="عدد المحكّمين لكل طلب",
                    ),
                ),
                (
                    "blind_judging",
                    models.BooleanField(
                        default=True,
                        help_text="المحكّم لا يرى اسم المدرسة ولا أسماء الطلبة والمشرف.",
                        verbose_name="تحكيم بدون أسماء؟",
                    ),
                ),
                (
                    "results_published",
                    models.BooleanField(
                        default=False,
                        help_text="قبل النشر ترى المدارس «قيد التحكيم» حتى لو حدّدتم النتيجة. عند النشر تُرسل الإشعارات للجميع.",
                        verbose_name="النتائج منشورة؟",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tracks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اتركها فارغة = كل المسارات المفعّلة.",
                        to="award.track",
                        verbose_name="المسارات المتاحة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دورة",
                "verbose_name_plural": "دورات الجائزة",
                "ordering": ["-year", "-opens_at"],
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="المعيار")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="شرح للمحكّم"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="الدرجة القصوى"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="1 = عادي، 2 = ضعف الأهمية.",
                        max_digits=4,
                        verbose_name="الوزن",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="فارغ = يُستخدم في كل الدورات.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="award.awardcycle",
                        verbose_name="الدورة",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        help_text="فارغ = لكل المسارات.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="award.track",
                        verbose_name="خاص بمسار",
                    ),
                ),
            ],
            options={
                "verbose_name": "معيار تحكيم",
                "verbose_name_plural": "معايير التحكيم",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("body", models.TextField(blank=True, default="", verbose_name="النص")),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="الرابط"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "معلومة"),
                            ("success", "نجاح"),
                            ("warning", "تنبيه"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء؟")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("school", "مدرسة"), ("judge", "محكّم")],
                        default="school",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="اسم المدرسة",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="الاسم / ضابط الارتباط",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="الهاتف"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="المدينة / المنطقة",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="التخصص (للمحكّم)",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="استلام الإشعارات بالبريد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "judge_fields",
                    models.ManyToManyField(
                        blank=True,
                        help_text="التوزيع التلقائي يُسند للمحكّم طلبات هذه المجالات فقط (فارغ = كل المجالات).",
                        to="award.field",
                        verbose_name="مجالات التحكيم",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب",
                "verbose_name_plural": "حسابات المدارس والمحكّمين",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="من"
                    ),
                ),
                ("new_status", models.CharField(max_length=20, verbose_name="إلى")),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="ملاحظة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بواسطة",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="award.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل حالة",
                "verbose_name_plural": "سجل الحالات",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="الدرجة"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="ملاحظة"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="award.assignment",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="award.criterion",
                        verbose_name="المعيار",
                    ),
                ),
            ],
            options={
                "verbose_name": "درجة",
                "verbose_name_plural": "الدرجات",
                "unique_together": {("assignment", "criterion")},
            },
        ),
    ]
