# Generated by Django 5.2.15 on 2026-10-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0043_registration_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اللواء / المدينة"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "لواء / مدينة",
                "verbose_name_plural": "الألوية والمدن",
                "ordering": ["governorate__order", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Directorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="مديرية التربية والتعليم"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهرة؟")),
            ],
            options={
                "verbose_name": "مديرية تربية",
                "verbose_name_plural": "مديريات التربية والتعليم",
                "ordering": ["governorate__order", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المحافظة"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
            ],
            options={
                "verbose_name": "محافظة",
                "verbose_name_plural": "المحافظات",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="المدينة / المنطقة (نص)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.area",
                verbose_name="اللواء / المدينة",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                help_text="عند اختيار هذه المدينة تُختار المديرية تلقائياً (يمكن للمدرسة تغييرها).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.directorate",
                verbose_name="المديرية التابعة لها (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.directorate",
                verbose_name="مديرية التربية",
            ),
        ),
        migrations.AddField(
            model_name="directorate",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                help_text="فارغ = يظهر في كل المحافظات (مثل: وكالة الغوث، أخرى).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directorates",
                to="award.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="governorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="award.governorate",
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="governorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.governorate",
                verbose_name="المحافظة",
            ),
        ),
    ]
