# Generated by Django 5.2.15 on 2026-10-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0045_jordan_locations_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_login_btn",
                    models.BooleanField(
                        default=True, verbose_name="إظهار زر «دخول» في الهيدر"
                    ),
                ),
                (
                    "login_btn_text",
                    models.CharField(
                        default="دخول", max_length=40, verbose_name="نص زر الدخول"
                    ),
                ),
                (
                    "account_btn_text",
                    models.CharField(
                        default="حسابي",
                        max_length=40,
                        verbose_name="نص الزر بعد الدخول",
                    ),
                ),
                (
                    "show_register_btn",
                    models.BooleanField(
                        default=True, verbose_name="إظهار زر «سجل الآن» في الهيدر"
                    ),
                ),
                (
                    "social_in_footer",
                    models.BooleanField(
                        default=True, verbose_name="شريط التواصل في الفوتر"
                    ),
                ),
                (
                    "social_in_menu",
                    models.BooleanField(
                        default=True, verbose_name="شريط التواصل في قائمة الموبايل"
                    ),
                ),
                (
                    "social_title",
                    models.CharField(
                        blank=True,
                        default="تابعونا",
                        max_length=100,
                        verbose_name="عنوان شريط التواصل (اختياري)",
                    ),
                ),
                (
                    "login_intro",
                    models.CharField(
                        default="لحسابات المدارس والمحكّمين.",
                        max_length=300,
                        verbose_name="نص صفحة الدخول",
                    ),
                ),
                (
                    "signup_title",
                    models.CharField(
                        default="حساب مدرسة جديد",
                        max_length=100,
                        verbose_name="عنوان صفحة التسجيل",
                    ),
                ),
                (
                    "signup_intro",
                    models.CharField(
                        default="أنشئوا حساباً مرة واحدة، ثم قدّموا مشاريعكم وتابعوا حالتها من مكان واحد.",
                        max_length=500,
                        verbose_name="نص صفحة التسجيل",
                    ),
                ),
                (
                    "submit_intro",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="مثال: شروط الملف، عدد الصفحات، آخر موعد…",
                        verbose_name="تعليمات أعلى نموذج تقديم المشروع (اختياري)",
                    ),
                ),
                (
                    "show_spam_hint",
                    models.BooleanField(
                        default=True, verbose_name="تنبيه المدارس لتفقّد مجلد Spam"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات الحسابات والهيدر والتواصل",
                "verbose_name_plural": "إعدادات الحسابات والهيدر والتواصل",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("x", "X (Twitter)"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("snapchat", "Snapchat"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("threads", "Threads"),
                            ("website", "موقع إلكتروني"),
                            ("email", "بريد إلكتروني"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="المنصة",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="مثال: https://www.instagram.com/iajaward — للبريد اكتب العنوان فقط، وللواتساب الرقم الدولي (9627xxxxxxxx).",
                        max_length=500,
                        verbose_name="الرابط",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اتركها فارغة لاستخدام أيقونة المنصة. مثال: fab fa-facebook-f",
                        max_length=60,
                        verbose_name="أيقونة مخصصة (اختياري)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="فارغ = لون الموقع الأساسي.",
                        max_length=7,
                        verbose_name="لون الأيقونة (اختياري)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر؟")),
            ],
            options={
                "verbose_name": "رابط تواصل اجتماعي",
                "verbose_name_plural": "روابط التواصل الاجتماعي",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="awardcycle",
            name="card_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="مثال: «تم تمديد التسجيل حتى نهاية الشهر».",
                verbose_name="سطر إضافي في بطاقة الدورة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="awardcycle",
            name="hijri_year",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مثال: 1448 — تظهر في بطاقة الدورة: «الدورة الرابعة عشرة (1448هـ/2026م)».",
                max_length=10,
                verbose_name="السنة الهجرية",
            ),
        ),
        migrations.AddField(
            model_name="awardcycle",
            name="show_card",
            field=models.BooleanField(
                default=True,
                verbose_name="إظهار بطاقة الدورة عند المرور على اسم الجائزة وزر التسجيل؟",
            ),
        ),
    ]
