# Generated by Django 5.2.15 on 2026-10-08 16:46

import award.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0048_social_demo_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardcycle",
            name="countdown_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = «استقبال طلبات» + الاسم المختصر.",
                max_length=120,
                verbose_name="عنوان بطاقة العداد (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="awardcycle",
            name="cover",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="cycles/",
                verbose_name="صورة الدورة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="awardcycle",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مثال: الدورة 14 — يظهر في بطاقة العداد: «استقبال طلبات الدورة 14».",
                max_length=60,
                verbose_name="اسم مختصر",
            ),
        ),
        migrations.AddField(
            model_name="awardcycle",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="نبذة عن الدورة (تظهر في صفحة الدورات السابقة)",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="caption",
            field=models.CharField(
                blank=True,
                default="",
                help_text="يظهر بجانب شعار الجائزة أعلى الصورة/الفيديو. فارغ = العنوان.",
                max_length=200,
                verbose_name="نص الشرح أعلى الصورة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="show_caption",
            field=models.BooleanField(
                default=True, verbose_name="إظهار نص الشرح أعلى الصورة؟"
            ),
        ),
        migrations.AddField(
            model_name="mediagallery",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="caption",
            field=models.CharField(
                blank=True,
                default="",
                help_text="يظهر بجانب شعار الجائزة أعلى الصورة/الفيديو. فارغ = العنوان.",
                max_length=200,
                verbose_name="نص الشرح أعلى الصورة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="show_caption",
            field=models.BooleanField(
                default=True, verbose_name="إظهار نص الشرح أعلى الصورة؟"
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="captions_enabled",
            field=models.BooleanField(
                default=True,
                verbose_name="إظهار نص الشرح بجانب الشعار (الصور والفيديو)",
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="countdown_badge",
            field=models.CharField(
                default="التسجيل مفتوح",
                help_text="يظهر لحظة تحميل الصفحة ثم يتحول إلى «باقي … يوماً».",
                max_length=40,
                verbose_name="نص زر العداد قبل الحساب",
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="show_cycle_filter",
            field=models.BooleanField(
                default=True,
                verbose_name="تصفية الصور والفيديو والأخبار حسب الدورة في الموقع",
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="wm_enabled",
            field=models.BooleanField(
                default=True, verbose_name="إظهار شعار الجائزة على الصور والفيديو"
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="wm_opacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.95,
                max_digits=3,
                verbose_name="شفافية الشعار (0–1)",
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="wm_position",
            field=models.CharField(
                choices=[("right", "أعلى اليمين"), ("left", "أعلى اليسار")],
                default="right",
                max_length=10,
                verbose_name="مكان الشعار",
            ),
        ),
        migrations.AddField(
            model_name="portalsetting",
            name="wm_size",
            field=models.PositiveSmallIntegerField(
                default=46, verbose_name="حجم الشعار (بكسل)"
            ),
        ),
        migrations.AddField(
            model_name="successstory",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="caption",
            field=models.CharField(
                blank=True,
                default="",
                help_text="يظهر بجانب شعار الجائزة أعلى الصورة/الفيديو. فارغ = العنوان.",
                max_length=200,
                verbose_name="نص الشرح أعلى الصورة (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="show_caption",
            field=models.BooleanField(
                default=True, verbose_name="إظهار نص الشرح أعلى الصورة؟"
            ),
        ),
        migrations.AddField(
            model_name="winner",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                default=award.models.current_cycle_id,
                help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="award.awardcycle",
                verbose_name="الدورة",
            ),
        ),
    ]
