# Generated by Django 5.2.15 on 2026-10-08 17:10

import award.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0051_open_first_cycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("school", "مدرسة"),
                    ("judge", "محكّم"),
                    ("manager", "إداري الجائزة"),
                ],
                default="school",
                max_length=10,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "مسودة"),
                    ("submitted", "مُرسل — بانتظار التدقيق"),
                    ("screening", "قيد التدقيق"),
                    ("revision", "مطلوب استكمال / تعديل"),
                    ("on_hold", "معلّق"),
                    ("judging", "قيد التحكيم"),
                    ("accepted", "مقبول"),
                    ("rejected", "غير مقبول"),
                    ("winner", "فائز"),
                    ("withdrawn", "مسحوب"),
                ],
                default="draft",
                max_length=20,
                verbose_name="الحالة",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="العنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "بطاقة نصية"),
                            ("media", "بطاقة وسائط (صور/فيديو)"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="نوع البطاقة",
                    ),
                ),
                ("body", models.TextField(blank=True, default="", verbose_name="النص")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="رابط زر (اختياري)",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="نص الزر"
                    ),
                ),
                (
                    "show_on_home",
                    models.BooleanField(
                        default=True, verbose_name="تظهر في الصفحة الرئيسية؟"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشور؟"),
                ),
                (
                    "pinned",
                    models.BooleanField(default=False, verbose_name="مثبّت أولاً؟"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="فارغ = تاريخ الإنشاء.",
                        null=True,
                        verbose_name="تاريخ النشر",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بواسطة",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        default=award.models.current_cycle_id,
                        help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="award.awardcycle",
                        verbose_name="الدورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعلان",
                "verbose_name_plural": "الإعلانات (بطاقات نصية ووسائط)",
                "ordering": ["-pinned", "-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to="announcements/",
                        verbose_name="صورة أو فيديو",
                    ),
                ),
                (
                    "youtube_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="أو رابط يوتيوب",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="نص الشرح"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="award.announcement",
                        verbose_name="الإعلان",
                    ),
                ),
            ],
            options={
                "verbose_name": "وسائط الإعلان",
                "verbose_name_plural": "وسائط الإعلان",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="JudgingCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم اللجنة")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="ملاحظات"),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__role": "judge"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chaired_committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رئيس اللجنة",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        default=award.models.current_cycle_id,
                        help_text="تُختار الدورة الحالية تلقائياً. فارغ = عام لكل الدورات.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="award.awardcycle",
                        verbose_name="الدورة",
                    ),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        blank=True,
                        help_text="فارغ = كل المجالات.",
                        to="award.field",
                        verbose_name="المجالات",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"profile__role": "judge"},
                        related_name="committees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الأعضاء (المحكّمون)",
                    ),
                ),
                (
                    "tracks",
                    models.ManyToManyField(
                        blank=True, to="award.track", verbose_name="المسارات (اختياري)"
                    ),
                ),
            ],
            options={
                "verbose_name": "لجنة تحكيم",
                "verbose_name_plural": "لجان التحكيم",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=award.models.extra_upload,
                        verbose_name="الملف",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="وصف الملف"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("video", "فيديو"),
                            ("audio", "صوت"),
                            ("doc", "مستند"),
                            ("archive", "ملف مضغوط"),
                            ("other", "أخرى"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(default=0, verbose_name="الحجم"),
                ),
                (
                    "after_submit",
                    models.BooleanField(
                        default=False, verbose_name="أُضيف بعد الإرسال؟"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="award.submission",
                        verbose_name="الطلب",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفعه",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف مرفق",
                "verbose_name_plural": "ملفات الطلبات المرفقة",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_staff",
                    models.BooleanField(
                        default=False, verbose_name="من إدارة الجائزة؟"
                    ),
                ),
                ("body", models.TextField(verbose_name="الرسالة")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=award.models.message_upload,
                        verbose_name="مرفق",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة؟")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="award.submission",
                        verbose_name="الطلب",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة على طلب",
                "verbose_name_plural": "مراسلات الطلبات",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
