# Generated by Django 5.2.15 on 2026-10-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0052_manager_console"),
    ]

    operations = [
        migrations.AddField(
            model_name="winner",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner_entry",
                to="award.submission",
                verbose_name="الطلب المرتبط",
            ),
        ),
    ]
