# Generated by Django 5.2.15 on 2026-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0056_theme_fonts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themesetting",
            name="primary_color",
            field=models.CharField(
                default="#0a1632",
                max_length=7,
                verbose_name="اللون الأساسي (لون الهيدر والقوائم)",
            ),
        ),
    ]
