# Generated by Django 5.2.15 on 2026-10-08 20:12

from django.db import migrations, models


def brown_card(apps, schema_editor):
    """طلب المستخدم: خلفية بطاقة النصوص بني داكن بدل الكحلي (لتناسب النص الذهبي)"""
    HeroCard = apps.get_model('award', 'HeroCard')
    for c in HeroCard.objects.all():
        c.card_bg_color = '#3b2614'
        if float(c.card_opacity or 0) < 0.8:
            c.card_opacity = 0.85
        c.save(update_fields=['card_bg_color', 'card_opacity'])


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0057_theme_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="herocard",
            name="heading_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = نفس «لون الخط».",
                max_length=9,
                verbose_name="لون العناوين داخل البطاقة",
            ),
        ),
        migrations.AddField(
            model_name="herotextslide",
            name="body_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = لون البطاقة.",
                max_length=9,
                verbose_name="لون النص (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="herotextslide",
            name="heading_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = لون البطاقة.",
                max_length=9,
                verbose_name="لون العنوان (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_body",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: النص العام في الصفحات",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_buttons",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="لون: نص الأزرار"
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_footer_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: نصوص وروابط الفوتر",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_footer_title",
            field=models.CharField(
                blank=True, default="", max_length=9, verbose_name="لون: عناوين الفوتر"
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_headings",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: عناوين الأقسام (كل الأقسام)",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_hero",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: النص المتحرك أعلى الصفحة (العنوان)",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_hero_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: النص المتحرك أعلى الصفحة (النص)",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_links",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: الروابط داخل النصوص",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_nav",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: روابط القائمة الرئيسية",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_numbers",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: أرقام العداد التنازلي",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_prize_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: نص بطاقات الجوائز",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_prize_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: عناوين بطاقات الجوائز",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_site_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: اسم الجائزة في الهيدر",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_tl_date",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: تواريخ الجدول الزمني",
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="color_tl_title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=9,
                verbose_name="لون: عناوين مراحل الجدول الزمني",
            ),
        ),
        migrations.RunPython(brown_card, migrations.RunPython.noop),
    ]
