# Generated by Django 5.2.15 on 2026-10-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0058_text_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herocard",
            name="card_bg_color",
            field=models.CharField(
                default="#3b2614", max_length=7, verbose_name="لون خلفية البطاقة"
            ),
        ),
    ]
