# Generated by Django 5.2.15 on 2026-10-08 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0059_card_brown_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="herocard",
            name="effect_speed",
            field=models.FloatField(
                default=0.6,
                help_text="مثال: 0.3 سريعة — 0.6 عادية — 1.5 بطيئة.",
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="مدة حركة الظهور للنص الأول (ثوانٍ)",
            ),
        ),
        migrations.AddField(
            model_name="herocard",
            name="roll_pause",
            field=models.FloatField(
                default=2.5,
                help_text="ليقرأ الزائر أول النص قبل أن يتحرك، وآخره قبل الانتقال.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="وقفة قبل بدء المرور وبعد انتهائه (ثوانٍ)",
            ),
        ),
        migrations.AddField(
            model_name="herocard",
            name="roll_speed",
            field=models.PositiveSmallIntegerField(
                default=22,
                help_text="العامة لكل النصوص. رقم أصغر = أبطأ. مثال: 12 بطيء — 22 عادي — 40 سريع.",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="سرعة مرور النص الطويل (بكسل/ثانية)",
            ),
        ),
        migrations.AddField(
            model_name="herotextslide",
            name="roll_speed",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="للنص الأطول من الصندوق (يمرّ مثل شارة الأفلام). رقم أصغر = أبطأ. مثال: 12 بطيء — 22 عادي — 40 سريع. 0 = سرعة البطاقة العامة.",
                validators=[django.core.validators.MaxValueValidator(200)],
                verbose_name="سرعة مرور النص الطويل (بكسل/ثانية)",
            ),
        ),
        migrations.AlterField(
            model_name="herotextslide",
            name="effect_speed",
            field=models.FloatField(
                default=0.6,
                help_text="كم ثانية تستغرق حركة دخول النص. مثال: 0.3 سريعة — 0.6 عادية — 1.5 بطيئة.",
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="مدة حركة الظهور (ثوانٍ)",
            ),
        ),
    ]
