# Generated by Django 5.2.15 on 2026-10-09 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0061_soften_navy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herocard",
            name="roll_pause",
            field=models.FloatField(
                default=2.5,
                help_text="ليقرأ الزائر أول النص قبل أن يصعد. بعد خروج النص كاملاً يظهر النص التالي مباشرة.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="وقفة قبل بدء مرور النص الطويل (ثوانٍ)",
            ),
        ),
    ]
