# Generated by Django 5.2.15 on 2026-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0062_roll_pause_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalsetting",
            name="show_hero_stats",
            field=models.BooleanField(
                default=True,
                help_text="المدارس المسجّلة، المشاريع، المجالات، المسارات — الرقم صفر لا يظهر.",
                verbose_name="إظهار أرقام الجائزة أعلى الصفحة الرئيسية (الكمبيوتر)",
            ),
        ),
    ]
