# Generated by Django 5.2.15 on 2026-10-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0063_hero_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homecontent",
            name="hero_subtitle",
            field=models.TextField(
                default="للثقافة والتعليم",
                help_text="سطر فارغ بين فقرتين = فقرة جديدة. سطر يبدأ بـ # = عنوان فرعي. مثال:\n# رؤيتنا\nنص الفقرة الأولى…",
                verbose_name="نص الشارة المتحركة (عدة فقرات)",
            ),
        ),
    ]
