# Generated by Django 5.2.15 on 2026-10-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0064_credits_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickeritem",
            name="heading",
            field=models.CharField(
                blank=True,
                default="",
                help_text="يظهر قبل النص داخل شارة ملوّنة. مثال: عاجل — جديد — تذكير",
                max_length=120,
                verbose_name="العنوان (اختياري)",
            ),
        ),
        migrations.AddField(
            model_name="tickeritem",
            name="heading_bg",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = لون خط الشريط (الذهبي)",
                max_length=9,
                verbose_name="لون خلفية العنوان",
            ),
        ),
        migrations.AddField(
            model_name="tickeritem",
            name="heading_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = لون داكن تلقائي",
                max_length=9,
                verbose_name="لون خط العنوان",
            ),
        ),
        migrations.AddField(
            model_name="tickeritem",
            name="text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="فارغ = لون خط الشريط من «إعدادات الشريط»",
                max_length=9,
                verbose_name="لون النص",
            ),
        ),
    ]
