# Generated by Django 5.2.15 on 2026-10-10 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("award", "0065_ticker_item_heading_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditsBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="العنوان (اختياري)",
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="سطر فارغ داخل النص = فقرة جديدة.",
                        verbose_name="النص (اختياري)",
                    ),
                ),
                (
                    "heading_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="فارغ = أبيض",
                        max_length=9,
                        verbose_name="لون العنوان",
                    ),
                ),
                (
                    "body_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="فارغ = أبيض",
                        max_length=9,
                        verbose_name="لون النص",
                    ),
                ),
                (
                    "heading_size",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="100 = الحجم العادي. 80 أصغر — 130 أكبر. يتناسب تلقائياً مع الهاتف.",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="حجم خط العنوان (%)",
                    ),
                ),
                (
                    "body_size",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="100 = الحجم العادي. 80 أصغر — 130 أكبر.",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="حجم خط النص (%)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="ظاهر؟")),
            ],
            options={
                "verbose_name": "فقرة في شارة الأفلام",
                "verbose_name_plural": "شارة الأفلام — الفقرات (عنوان + نص + لون + حجم)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="homecontent",
            name="credits_speed",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="رقم أكبر = أسرع. 10 بطيء — 14 عادي — 25 سريع.",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(80),
                ],
                verbose_name="سرعة شارة الأفلام (بكسل/ثانية)",
            ),
        ),
    ]
